/**
 * Country -> currency lookup for the "إضافة عملة جديدة" form (Settings -> العملات وأسعار الصرف).
 * Picking a country auto-fills its currency's code/name/symbol so the operator only has to type
 * the exchange rate - this is display data only, never a source of truth for rates (those always
 * come from the operator, see currencyStore.ts).
 */

export interface CountryCurrencyOption {
  /** Arabic country name shown in the picker - unique, doubles as the picker's own key/value. */
  country: string;
  /** ISO 4217 code, uppercase. */
  code: string;
  /** Arabic currency name, stored as Currency.name. */
  name: string;
  symbol: string;
}

export const COUNTRY_CURRENCIES: CountryCurrencyOption[] = [
  { country: "الولايات المتحدة الأمريكية", code: "USD", name: "دولار أمريكي", symbol: "$" },

  // إفريقيا
  { country: "الجزائر", code: "DZD", name: "دينار جزائري", symbol: "DZD" },
  { country: "أنغولا", code: "AOA", name: "كوانزا أنغولي", symbol: "AOA" },
  { country: "بنين", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "بوتسوانا", code: "BWP", name: "بولا بوتسوانية", symbol: "BWP" },
  { country: "بوركينا فاسو", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "بوروندي", code: "BIF", name: "فرنك بوروندي", symbol: "BIF" },
  { country: "الرأس الأخضر", code: "CVE", name: "إسكودو الرأس الأخضر", symbol: "CVE" },
  { country: "الكاميرون", code: "XAF", name: "فرنك وسط إفريقي", symbol: "XAF" },
  { country: "جمهورية إفريقيا الوسطى", code: "XAF", name: "فرنك وسط إفريقي", symbol: "XAF" },
  { country: "تشاد", code: "XAF", name: "فرنك وسط إفريقي", symbol: "XAF" },
  { country: "جزر القمر", code: "KMF", name: "فرنك قمري", symbol: "KMF" },
  { country: "جمهورية الكونغو", code: "XAF", name: "فرنك وسط إفريقي", symbol: "XAF" },
  { country: "جمهورية الكونغو الديمقراطية", code: "CDF", name: "فرنك كونغولي", symbol: "CDF" },
  { country: "ساحل العاج", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "جيبوتي", code: "DJF", name: "فرنك جيبوتي", symbol: "DJF" },
  { country: "مصر", code: "EGP", name: "جنيه مصري", symbol: "EGP" },
  { country: "غينيا الاستوائية", code: "XAF", name: "فرنك وسط إفريقي", symbol: "XAF" },
  { country: "إريتريا", code: "ERN", name: "ناكفا إريترية", symbol: "ERN" },
  { country: "إسواتيني", code: "SZL", name: "ليلانجيني", symbol: "SZL" },
  { country: "إثيوبيا", code: "ETB", name: "بير إثيوبي", symbol: "ETB" },
  { country: "الغابون", code: "XAF", name: "فرنك وسط إفريقي", symbol: "XAF" },
  { country: "غامبيا", code: "GMD", name: "دالاسي غامبي", symbol: "GMD" },
  { country: "غانا", code: "GHS", name: "سيدي غاني", symbol: "GHS" },
  { country: "غينيا", code: "GNF", name: "فرنك غيني", symbol: "GNF" },
  { country: "غينيا بيساو", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "كينيا", code: "KES", name: "شلن كيني", symbol: "KES" },
  { country: "ليسوتو", code: "LSL", name: "لوتي ليسوتو", symbol: "LSL" },
  { country: "ليبيريا", code: "LRD", name: "دولار ليبيري", symbol: "LRD" },
  { country: "ليبيا", code: "LYD", name: "دينار ليبي", symbol: "LYD" },
  { country: "مدغشقر", code: "MGA", name: "أرياري مدغشقري", symbol: "MGA" },
  { country: "مالاوي", code: "MWK", name: "كواشا ملاوية", symbol: "MWK" },
  { country: "مالي", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "موريتانيا", code: "MRU", name: "أوقية موريتانية", symbol: "MRU" },
  { country: "موريشيوس", code: "MUR", name: "روبية موريشيوسية", symbol: "MUR" },
  { country: "المغرب", code: "MAD", name: "درهم مغربي", symbol: "MAD" },
  { country: "موزمبيق", code: "MZN", name: "متيكال موزمبيقي", symbol: "MZN" },
  { country: "ناميبيا", code: "NAD", name: "دولار ناميبي", symbol: "NAD" },
  { country: "النيجر", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "نيجيريا", code: "NGN", name: "نايرا نيجيرية", symbol: "NGN" },
  { country: "رواندا", code: "RWF", name: "فرنك رواندي", symbol: "RWF" },
  { country: "ساو تومي وبرينسيب", code: "STN", name: "دوبرا ساو تومي", symbol: "STN" },
  { country: "السنغال", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "سيشيل", code: "SCR", name: "روبية سيشيلية", symbol: "SCR" },
  { country: "سيراليون", code: "SLE", name: "ليون سيراليوني", symbol: "SLE" },
  { country: "الصومال", code: "SOS", name: "شلن صومالي", symbol: "SOS" },
  { country: "جنوب أفريقيا", code: "ZAR", name: "راند جنوب أفريقي", symbol: "ZAR" },
  { country: "جنوب السودان", code: "SSP", name: "جنيه جنوب سوداني", symbol: "SSP" },
  { country: "السودان", code: "SDG", name: "جنيه سوداني", symbol: "SDG" },
  { country: "تنزانيا", code: "TZS", name: "شلن تنزاني", symbol: "TZS" },
  { country: "توغو", code: "XOF", name: "فرنك غرب إفريقي", symbol: "XOF" },
  { country: "تونس", code: "TND", name: "دينار تونسي", symbol: "TND" },
  { country: "أوغندا", code: "UGX", name: "شلن أوغندي", symbol: "UGX" },
  { country: "زامبيا", code: "ZMW", name: "كواشا زامبية", symbol: "ZMW" },
  { country: "زيمبابوي", code: "ZWL", name: "دولار زيمبابوي", symbol: "ZWL" },

  // آسيا
  { country: "أفغانستان", code: "AFN", name: "أفغاني", symbol: "AFN" },
  { country: "أرمينيا", code: "AMD", name: "درام أرميني", symbol: "AMD" },
  { country: "أذربيجان", code: "AZN", name: "مانات أذربيجاني", symbol: "AZN" },
  { country: "البحرين", code: "BHD", name: "دينار بحريني", symbol: "BHD" },
  { country: "بنغلاديش", code: "BDT", name: "تاكا بنغلاديشية", symbol: "BDT" },
  { country: "بوتان", code: "BTN", name: "نغولتروم بوتاني", symbol: "BTN" },
  { country: "بروناي", code: "BND", name: "دولار بروناي", symbol: "BND" },
  { country: "كمبوديا", code: "KHR", name: "رييل كمبودي", symbol: "KHR" },
  { country: "الصين", code: "CNY", name: "يوان صيني", symbol: "CNY" },
  { country: "جورجيا", code: "GEL", name: "لاري جورجي", symbol: "GEL" },
  { country: "الهند", code: "INR", name: "روبية هندية", symbol: "₹" },
  { country: "إندونيسيا", code: "IDR", name: "روبية إندونيسية", symbol: "IDR" },
  { country: "إيران", code: "IRR", name: "ريال إيراني", symbol: "IRR" },
  { country: "العراق", code: "IQD", name: "دينار عراقي", symbol: "IQD" },
  { country: "إسرائيل", code: "ILS", name: "شيكل جديد", symbol: "₪" },
  { country: "اليابان", code: "JPY", name: "ين ياباني", symbol: "¥" },
  { country: "الأردن", code: "JOD", name: "دينار أردني", symbol: "JOD" },
  { country: "كازاخستان", code: "KZT", name: "تنغي كازاخستاني", symbol: "KZT" },
  { country: "الكويت", code: "KWD", name: "دينار كويتي", symbol: "KWD" },
  { country: "قيرغيزستان", code: "KGS", name: "سوم قيرغيزستاني", symbol: "KGS" },
  { country: "لاوس", code: "LAK", name: "كيب لاوسي", symbol: "LAK" },
  { country: "لبنان", code: "LBP", name: "ليرة لبنانية", symbol: "LBP" },
  { country: "ماليزيا", code: "MYR", name: "رينغيت ماليزي", symbol: "MYR" },
  { country: "جزر المالديف", code: "MVR", name: "روفية مالديفية", symbol: "MVR" },
  { country: "منغوليا", code: "MNT", name: "توغروغ منغولي", symbol: "MNT" },
  { country: "ميانمار", code: "MMK", name: "كيات ميانماري", symbol: "MMK" },
  { country: "نيبال", code: "NPR", name: "روبية نيبالية", symbol: "NPR" },
  { country: "كوريا الشمالية", code: "KPW", name: "وون كوري شمالي", symbol: "KPW" },
  { country: "عُمان", code: "OMR", name: "ريال عماني", symbol: "OMR" },
  { country: "باكستان", code: "PKR", name: "روبية باكستانية", symbol: "PKR" },
  { country: "فلسطين", code: "ILS", name: "شيكل جديد", symbol: "₪" },
  { country: "الفلبين", code: "PHP", name: "بيزو فلبيني", symbol: "PHP" },
  { country: "قطر", code: "QAR", name: "ريال قطري", symbol: "QAR" },
  { country: "المملكة العربية السعودية", code: "SAR", name: "ريال سعودي", symbol: "SAR" },
  { country: "سنغافورة", code: "SGD", name: "دولار سنغافوري", symbol: "SGD" },
  { country: "كوريا الجنوبية", code: "KRW", name: "وون كوري جنوبي", symbol: "KRW" },
  { country: "سريلانكا", code: "LKR", name: "روبية سريلانكية", symbol: "LKR" },
  { country: "سوريا", code: "SYP", name: "ليرة سورية", symbol: "SYP" },
  { country: "تايوان", code: "TWD", name: "دولار تايواني جديد", symbol: "TWD" },
  { country: "طاجيكستان", code: "TJS", name: "سوموني طاجيكستاني", symbol: "TJS" },
  { country: "تايلاند", code: "THB", name: "بات تايلاندي", symbol: "THB" },
  { country: "تيمور الشرقية", code: "USD", name: "دولار أمريكي", symbol: "$" },
  { country: "تركيا", code: "TRY", name: "ليرة تركية", symbol: "TRY" },
  { country: "تركمانستان", code: "TMT", name: "مانات تركمانستاني", symbol: "TMT" },
  { country: "الإمارات العربية المتحدة", code: "AED", name: "درهم إماراتي", symbol: "AED" },
  { country: "أوزبكستان", code: "UZS", name: "سوم أوزبكستاني", symbol: "UZS" },
  { country: "فيتنام", code: "VND", name: "دونغ فيتنامي", symbol: "VND" },
  { country: "اليمن", code: "YER", name: "ريال يمني", symbol: "YER" },

  // أوروبا
  { country: "ألبانيا", code: "ALL", name: "ليك ألباني", symbol: "ALL" },
  { country: "أندورا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "النمسا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "بيلاروسيا", code: "BYN", name: "روبل بيلاروسي", symbol: "BYN" },
  { country: "بلجيكا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "البوسنة والهرسك", code: "BAM", name: "مارك بوسني", symbol: "BAM" },
  { country: "بلغاريا", code: "BGN", name: "ليف بلغاري", symbol: "BGN" },
  { country: "كرواتيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "قبرص", code: "EUR", name: "يورو", symbol: "€" },
  { country: "جمهورية التشيك", code: "CZK", name: "كورونا تشيكية", symbol: "CZK" },
  { country: "الدنمارك", code: "DKK", name: "كرونة دنماركية", symbol: "DKK" },
  { country: "إستونيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "فنلندا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "فرنسا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "ألمانيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "اليونان", code: "EUR", name: "يورو", symbol: "€" },
  { country: "المجر", code: "HUF", name: "فورنت مجري", symbol: "HUF" },
  { country: "آيسلندا", code: "ISK", name: "كرونة آيسلندية", symbol: "ISK" },
  { country: "أيرلندا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "إيطاليا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "كوسوفو", code: "EUR", name: "يورو", symbol: "€" },
  { country: "لاتفيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "ليختنشتاين", code: "CHF", name: "فرنك سويسري", symbol: "CHF" },
  { country: "ليتوانيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "لوكسمبورغ", code: "EUR", name: "يورو", symbol: "€" },
  { country: "مالطا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "مولدوفا", code: "MDL", name: "ليو مولدوفي", symbol: "MDL" },
  { country: "موناكو", code: "EUR", name: "يورو", symbol: "€" },
  { country: "الجبل الأسود", code: "EUR", name: "يورو", symbol: "€" },
  { country: "هولندا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "مقدونيا الشمالية", code: "MKD", name: "دينار مقدوني", symbol: "MKD" },
  { country: "النرويج", code: "NOK", name: "كرونة نرويجية", symbol: "NOK" },
  { country: "بولندا", code: "PLN", name: "زلوتي بولندي", symbol: "PLN" },
  { country: "البرتغال", code: "EUR", name: "يورو", symbol: "€" },
  { country: "رومانيا", code: "RON", name: "ليو روماني", symbol: "RON" },
  { country: "روسيا", code: "RUB", name: "روبل روسي", symbol: "RUB" },
  { country: "سان مارينو", code: "EUR", name: "يورو", symbol: "€" },
  { country: "صربيا", code: "RSD", name: "دينار صربي", symbol: "RSD" },
  { country: "سلوفاكيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "سلوفينيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "إسبانيا", code: "EUR", name: "يورو", symbol: "€" },
  { country: "السويد", code: "SEK", name: "كرونة سويدية", symbol: "SEK" },
  { country: "سويسرا", code: "CHF", name: "فرنك سويسري", symbol: "CHF" },
  { country: "أوكرانيا", code: "UAH", name: "غريفنا أوكرانية", symbol: "UAH" },
  { country: "المملكة المتحدة", code: "GBP", name: "جنيه إسترليني", symbol: "£" },
  { country: "الفاتيكان", code: "EUR", name: "يورو", symbol: "€" },

  // الأمريكتان
  { country: "أنتيغوا وباربودا", code: "XCD", name: "دولار شرق الكاريبي", symbol: "XCD" },
  { country: "الأرجنتين", code: "ARS", name: "بيزو أرجنتيني", symbol: "ARS" },
  { country: "جزر البهاما", code: "BSD", name: "دولار بهامي", symbol: "BSD" },
  { country: "بربادوس", code: "BBD", name: "دولار بربادوسي", symbol: "BBD" },
  { country: "بليز", code: "BZD", name: "دولار بليزي", symbol: "BZD" },
  { country: "بوليفيا", code: "BOB", name: "بوليفيانو", symbol: "BOB" },
  { country: "البرازيل", code: "BRL", name: "ريال برازيلي", symbol: "BRL" },
  { country: "كندا", code: "CAD", name: "دولار كندي", symbol: "CAD" },
  { country: "شيلي", code: "CLP", name: "بيزو تشيلي", symbol: "CLP" },
  { country: "كولومبيا", code: "COP", name: "بيزو كولومبي", symbol: "COP" },
  { country: "كوستاريكا", code: "CRC", name: "كولون كوستاريكي", symbol: "CRC" },
  { country: "كوبا", code: "CUP", name: "بيزو كوبي", symbol: "CUP" },
  { country: "دومينيكا", code: "XCD", name: "دولار شرق الكاريبي", symbol: "XCD" },
  { country: "جمهورية الدومينيكان", code: "DOP", name: "بيزو دومينيكاني", symbol: "DOP" },
  { country: "الإكوادور", code: "USD", name: "دولار أمريكي", symbol: "$" },
  { country: "السلفادور", code: "USD", name: "دولار أمريكي", symbol: "$" },
  { country: "غرينادا", code: "XCD", name: "دولار شرق الكاريبي", symbol: "XCD" },
  { country: "غواتيمالا", code: "GTQ", name: "كتزال غواتيمالي", symbol: "GTQ" },
  { country: "غيانا", code: "GYD", name: "دولار غياني", symbol: "GYD" },
  { country: "هايتي", code: "HTG", name: "غورد هايتي", symbol: "HTG" },
  { country: "هندوراس", code: "HNL", name: "ليمبيرا هندوراسية", symbol: "HNL" },
  { country: "جامايكا", code: "JMD", name: "دولار جامايكي", symbol: "JMD" },
  { country: "المكسيك", code: "MXN", name: "بيزو مكسيكي", symbol: "MXN" },
  { country: "نيكاراغوا", code: "NIO", name: "كوردوبا نيكاراغوية", symbol: "NIO" },
  { country: "بنما", code: "PAB", name: "بالبوا بنمي", symbol: "PAB" },
  { country: "باراغواي", code: "PYG", name: "غواراني باراغواي", symbol: "PYG" },
  { country: "بيرو", code: "PEN", name: "سول بيروفي", symbol: "PEN" },
  { country: "سانت كيتس ونيفيس", code: "XCD", name: "دولار شرق الكاريبي", symbol: "XCD" },
  { country: "سانت لوسيا", code: "XCD", name: "دولار شرق الكاريبي", symbol: "XCD" },
  { country: "سانت فينسنت والغرينادين", code: "XCD", name: "دولار شرق الكاريبي", symbol: "XCD" },
  { country: "سورينام", code: "SRD", name: "دولار سورينامي", symbol: "SRD" },
  { country: "ترينيداد وتوباغو", code: "TTD", name: "دولار ترينيدادي", symbol: "TTD" },
  { country: "أوروغواي", code: "UYU", name: "بيزو أوروغواياني", symbol: "UYU" },
  { country: "فنزويلا", code: "VES", name: "بوليفار فنزويلي", symbol: "VES" },

  // أوقيانوسيا
  { country: "أستراليا", code: "AUD", name: "دولار أسترالي", symbol: "AUD" },
  { country: "فيجي", code: "FJD", name: "دولار فيجي", symbol: "FJD" },
  { country: "كيريباتي", code: "AUD", name: "دولار أسترالي", symbol: "AUD" },
  { country: "جزر مارشال", code: "USD", name: "دولار أمريكي", symbol: "$" },
  { country: "ميكرونيزيا", code: "USD", name: "دولار أمريكي", symbol: "$" },
  { country: "ناورو", code: "AUD", name: "دولار أسترالي", symbol: "AUD" },
  { country: "نيوزيلندا", code: "NZD", name: "دولار نيوزيلندي", symbol: "NZD" },
  { country: "بالاو", code: "USD", name: "دولار أمريكي", symbol: "$" },
  { country: "بابوا غينيا الجديدة", code: "PGK", name: "كينا بابوا غينيا الجديدة", symbol: "PGK" },
  { country: "ساموا", code: "WST", name: "تالا ساموي", symbol: "WST" },
  { country: "جزر سليمان", code: "SBD", name: "دولار جزر سليمان", symbol: "SBD" },
  { country: "تونغا", code: "TOP", name: "بعانغا تونغية", symbol: "TOP" },
  { country: "توفالو", code: "AUD", name: "دولار أسترالي", symbol: "AUD" },
  { country: "فانواتو", code: "VUV", name: "فاتو فانواتو", symbol: "VUV" },
];
