import { DeviceStatus, StarlinkAccountSummary } from "@starnet/shared";

/**
 * DEMO DATA ONLY - fictional accounts for the public GitHub Pages preview.
 * No real customer names, credentials, KIT/serial numbers, or Starlink data
 * may ever be added to this file. See docs/ARCHITECTURE.md "Public preview
 * safety".
 */
export const demoAccounts: StarlinkAccountSummary[] = [
  {
    id: "demo-1",
    customerId: "demo-customer-1",
    name: "مقهى النخيل",
    deviceName: "Standard Kit",
    kitNumber: "DEMO-KIT-0001",
    serialNumber: "DEMO-SER-0001",
    standbyDate: "",
    rechargeDate: "2026/09/18",
    balanceDue: "0",
    currency: "$",
    dishStatus: DeviceStatus.GREEN,
    wifiStatus: DeviceStatus.GREEN,
    alertReason: "",
    lastUpdated: "منذ 5 دقائق",
    lastSuccessfulScanAt: new Date().toISOString(),
    planName: "Priority 40GB",
  },
  {
    id: "demo-2",
    customerId: "demo-customer-2",
    name: "فيلا الياسمين",
    deviceName: "Standard Kit",
    kitNumber: "DEMO-KIT-0002",
    serialNumber: "DEMO-SER-0002",
    standbyDate: "",
    rechargeDate: "2026/09/16",
    balanceDue: "12.50",
    currency: "$",
    dishStatus: DeviceStatus.YELLOW,
    wifiStatus: DeviceStatus.GREEN,
    alertReason: "الرصيد منخفض",
    lastUpdated: "منذ ساعة",
    lastSuccessfulScanAt: new Date().toISOString(),
    planName: "Residential",
  },
  {
    id: "demo-3",
    customerId: "demo-customer-3",
    name: "سوبر ماركت الأمل",
    deviceName: "Standard Kit",
    kitNumber: "DEMO-KIT-0003",
    serialNumber: "DEMO-SER-0003",
    standbyDate: "2026/09/10",
    rechargeDate: "2026/09/10",
    balanceDue: "40.00",
    currency: "$",
    dishStatus: DeviceStatus.RED,
    wifiStatus: DeviceStatus.RED,
    alertReason: "منتهي - يحتاج تجديد فوري",
    lastUpdated: "منذ يومين",
    lastSuccessfulScanAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    planName: "Priority 40GB",
  },
  {
    id: "demo-4",
    customerId: "demo-customer-4",
    name: "مكتب المحاماة - المبنى الإداري",
    deviceName: "Standard Kit",
    kitNumber: "DEMO-KIT-0004",
    serialNumber: "DEMO-SER-0004",
    standbyDate: "",
    rechargeDate: "2026/09/28",
    balanceDue: "0",
    currency: "$",
    dishStatus: DeviceStatus.GRAY,
    wifiStatus: DeviceStatus.GRAY,
    alertReason: "",
    lastUpdated: "منذ 6 أيام",
    lastSuccessfulScanAt: null,
    planName: "Business",
  },
  {
    id: "demo-5",
    customerId: "demo-customer-5",
    name: "استراحة الواحة",
    deviceName: "Standard Kit",
    kitNumber: "DEMO-KIT-0005",
    serialNumber: "DEMO-SER-0005",
    standbyDate: "",
    rechargeDate: "2026/09/18",
    balanceDue: "5.00",
    currency: "$",
    dishStatus: DeviceStatus.GREEN,
    wifiStatus: DeviceStatus.GREEN,
    alertReason: "",
    lastUpdated: "منذ 10 دقائق",
    lastSuccessfulScanAt: new Date().toISOString(),
    planName: "Residential Lite",
  },
];
